Crear Tablas
CREATE TABLE RAMDATOSPREVENCION (		IEJERCICIO INTEGER NOT NULL,		ICVESOLICITUD INTEGER NOT NULL,		ICVESUPUESTO INTEGER,		CRESPONSABLE VARCHAR(250),		CLEYENDA VARCHAR(600),		CINICIALES VARCHAR(50),		CSOLICITUD VARCHAR(40),		CPUESTO VARCHAR(90),		CFOLIO VARCHAR(25),		Columna1 CHAR(5)	) DATA CAPTURE NONE IN USERSPACE1 ;
ALTER TABLE RAMDATOSPREVENCION ADD CONSTRAINT RAMDATOSPREVENCION_PK PRIMARY KEY	(IEJERCICIO,	 ICVESOLICITUD);
GRANT ALTER ON TABLE RAMDATOSPREVENCION TO USER DB2INST1 WITH GRANT OPTION;
CREATE PUBLIC ALIAS "RAMDATOSPREVENCION" FOR "ESIPYMM"."RAMDATOSPREVENCION";

Modificar Tablas
ALTER TABLE RAMCERTIFICADO ADD COLUMN ICVECORRELATIVO INT NULL;
ALTER TABLE RAMCERTIFICADO ADD COLUMN COBSERVACIONES2 VARCHAR(500) NULL;
ALTER TABLE RAMREGISTRO ADD COLUMN  CPUESTO VARCHAR(90) NULL;
ALTER TABLE RAMREGISTRO ADD COLUMN CSOLICITUD VARCHAR(40) NULL; 

ALTER TABLE "ESIPYMM"."INSREGISTRO" DROP CONSTRAINT "R_126";
ALTER TABLE "ESIPYMM"."ACCREGACCINC" DROP CONSTRAINT "R_139";
ALTER TABLE "ESIPYMM"."RAMALERTA" DROP CONSTRAINT "R_138";
ALTER TABLE "ESIPYMM"."RAMCERTIFICADO" DROP CONSTRAINT "R_73";
DROP ALIAS "DB2UPAMM"."RAMREGISTRO";
DROP ALIAS "DB2UPCMM"."RAMREGISTRO";
DROP ALIAS "DB2UPWMM"."RAMREGISTRO";
DROP ALIAS "ENLACE"."RAMREGISTRO";
ALTER TABLE "ESIPYMM"."RAMREGISTRO" ADD COLUMN "ICVECORRELATIVO" INTEGER;
ALTER TABLE "ESIPYMM"."INSREGISTRO" ADD CONSTRAINT "R_126" FOREIGN KEY
	("ICVEREGISTRORAM")
	REFERENCES "ESIPYMM"."RAMREGISTRO"
	("ICVEREGISTRO");
ALTER TABLE "ESIPYMM"."ACCREGACCINC" ADD CONSTRAINT "R_139" FOREIGN KEY
	("ICVEREGISTRORAM")
	REFERENCES "ESIPYMM"."RAMREGISTRO"
	("ICVEREGISTRO");
ALTER TABLE "ESIPYMM"."RAMALERTA" ADD CONSTRAINT "R_138" FOREIGN KEY
	("ICVEREGISTRORAM")
	REFERENCES "ESIPYMM"."RAMREGISTRO"
	("ICVEREGISTRO");
ALTER TABLE "ESIPYMM"."RAMCERTIFICADO" ADD CONSTRAINT "R_73" FOREIGN KEY
	("ICVEREGISTRO")
	REFERENCES "ESIPYMM"."RAMREGISTRO"
	("ICVEREGISTRO");
CREATE ALIAS "DB2UPAMM"."RAMREGISTRO" FOR "ESIPYMM"."RAMREGISTRO";
CREATE ALIAS "DB2UPCMM"."RAMREGISTRO" FOR "ESIPYMM"."RAMREGISTRO";
CREATE ALIAS "DB2UPWMM"."RAMREGISTRO" FOR "ESIPYMM"."RAMREGISTRO";
CREATE ALIAS "ENLACE"."RAMREGISTRO" FOR "ESIPYMM"."RAMREGISTRO";


Insertar en tablas
insert into segprograma (ICVESISTEMA, ICVEPROGRAMA, CNOMBRE , CDSCPROGRAMA , LTIENEESCRITURA, LCONFIGURABLE, LBLOQUEADO, LFIEL ) values  (22, 30088, 'pgRegistraPagopost',  'POSTPAGORAM', 1, 1, 0 , 0 );
insert into segpermisoxgpo (ICVESISTEMA, ICVEGRUPO, ICVEPROGRAMA, LEJECUCION, LACTUALIZACION)  values ( 22 , 68 , 30088 , 1 , 1 );
insert into segprograma (ICVESISTEMA, ICVEPROGRAMA, CNOMBRE , CDSCPROGRAMA , LTIENEESCRITURA, LCONFIGURABLE, LBLOQUEADO, LFIEL ) values  (22, 30089, 'pg22GrlRAMHist',  'Historico RAM', 1, 1, 0 , 0 );
insert into segpermisoxgpo (ICVESISTEMA, ICVEGRUPO, ICVEPROGRAMA, LEJECUCION, LACTUALIZACION) values ( 22 , 68 , 30089 , 1 , 1 );
insert into segmenu ( IORDEN,ICVESISTEMA,CDSCMENU,CREFERENCIA,IOPCPADRE,LBLOQUEADO,CNOMPAGINA ) values   ( 5070240,22,'Consulta Historico RAM',  'pg22GrlRAMHist',  5070200 , 0 ,'pg22GrlRAMHist');

Crear Menus de programas
insert into segprograma (ICVESISTEMA, ICVEPROGRAMA, CNOMBRE , CDSCPROGRAMA , LTIENEESCRITURA, LCONFIGURABLE, LBLOQUEADO, LFIEL ) values  (22, 30088, 'pgRegistraPagopost',  'POSTPAGORAM', 1, 1, 0 , 0 );
insert into segpermisoxgpo (ICVESISTEMA, ICVEGRUPO, ICVEPROGRAMA, LEJECUCION, LACTUALIZACION)  values ( 22 , 68 , 30088 , 1 , 1 );
insert into segprograma (ICVESISTEMA, ICVEPROGRAMA, CNOMBRE , CDSCPROGRAMA , LTIENEESCRITURA, LCONFIGURABLE, LBLOQUEADO, LFIEL ) values  (22, 30089, 'pg22GrlRAMHist',  'Historico RAM', 1, 1, 0 , 0 );
insert into segpermisoxgpo (ICVESISTEMA, ICVEGRUPO, ICVEPROGRAMA, LEJECUCION, LACTUALIZACION) values ( 22 , 68 , 30089 , 1 , 1 );
insert into segmenu ( IORDEN,ICVESISTEMA,CDSCMENU,CREFERENCIA,IOPCPADRE,LBLOQUEADO,CNOMPAGINA ) values   ( 5070240,22,'Consulta Historico RAM',  'pg22GrlRAMHist',  5070200 , 0 ,'pg22GrlRAMHist');


Crear REportes
insert into grlreporte (ICVESISTEMA, ICVEMODULO, INUMREPORTE, CNOMREPORTE,LEXCEL, LWORD, LPDF, LMULTIPART,  CPLANTILLAPDF , CDAOEJECUTAR, CMETODOPDF, ICVEFORMATOFILTRO, LAUTOIMPRIMIR, INUMCOPIAS, LMOSTRARAPLICACION, LPARAMETROMODIFICABLE, LREQUIEREFOLIO  ) values (22,6,3,'PREVENCION',0,0,1,0,'PrevenRAM','.reporte.TDReporteTramite069','oficioPrevencionRAM2',0,0,0,0,0,0);
insert into grlreporte (ICVESISTEMA, ICVEMODULO, INUMREPORTE, CNOMREPORTE,LEXCEL, LWORD, LPDF, LMULTIPART,  CPLANTILLAPDF , CDAOEJECUTAR, CMETODOPDF, ICVEFORMATOFILTRO, LAUTOIMPRIMIR, INUMCOPIAS, LMOSTRARAPLICACION, LPARAMETROMODIFICABLE, LREQUIEREFOLIO  ) values (22,6,2,'PREVENCION',0,0,1,0,'PrevenRAM','.reporte.TDReporteTramite069','oficioPrevencionRAM',0,0,0,0,0,0);
